### ISSUE TITLE
[TALK] Introduction to GitHub - VG

### ISSUE THREAD

**Issue by vipulgupta2048** [asetalias/Logistics-and-Event-Contributions#1]
Beginner level talk on Git, GitHub, Git workflow and a cool story. No background knowledge needed to understand. Harness the power of Git to make your projects stable, organised and secure increasing both efficiency and productivity. #HandsOn.
Prerequisite - Laptop, brain and fingers.

**Comment by Tanya-Jain** [comment]
Your talk was planned for Saturday, September 9. Due to this being a regular working day as well, when do you wish to give your talk?

**Comment by vipulgupta2048** [comment]
My talk is almost ready and as discussed with Ajay. We are thinking Thursday to be the best time. For the talk. I will start promotions Monday. Just discuss between yourselves. Who is going to organize it ? Speakers don't participate in that discussion.

**Comment by Tanya-Jain** [comment]
The talk has finally taken place on 25 January 2018 titled "CSE Essentials". Please share the talk slides.

**Comment by vipulgupta2048** [comment]
Slide links - https://docs.google.com/presentation/d/1dLshLydrBL8t_X3nvOodi-LkH8iORocy8uadGrlslGc/edit?usp=sharing
Demo repo - www.github.com/vipulgupta2048/vanilla
