### ISSUE TITLE
[Talk] Introduction to Raspberry pi and its applications in IoT

### ISSUE THREAD

**Issue by sjha2000** [asetalias/Logistics-and-Event-Contributions#15]
This will help you to learn basic aspects of IoT ,
It's amazing to see that only a few years back, it was virtually impossible for someone to have access to actual hardware to run IoT solutions. That is, cheap and reasonably-sized equipment that you could easily deploy in a house, a car, ... Nowadays, platforms like Arduino, mbed, BeagleBone and Raspberry Pi are providing IoT developers with a wide ecosystem of hardware that can be used to easily prototype and even go to production for small batches.

Type :- Hands on
proposed date :- 8th of march
expected duration :- 3hrs.
requirements :- projector, hdmi to vga convertor, keyboard.

**Comment by vipulgupta2048** [comment]
+1
Any prerequisites for the talk?

Cordially,
Vipul

**Comment by sjha2000** [comment]
Prerequisites :-
Nothing great just some interest
And basic knowledge of  ssh,IP and linux

**Comment by Tanya-Jain** [comment]
Kindly put the link to your slides

**Comment by sjha2000** [comment]
Link to slides :- https://goo.gl/RXa4qC
