### ISSUE TITLE
[Webinar] Wireless Networking and Use of Kali Linux on Wireless Networking

### ISSUE THREAD

**Issue by thisisayush** [asetalias/Logistics-and-Event-Contributions#17]
# Wireless Networking and Use of Kali Linux on Wireless Networking
**Type**
- [ ] Workshop / Hands on
- [ ] Guest Lecture
- [x] Webinar

**Abstract**

Awaiting Details from Speaker

**About**

Awaiting Details from Speaker.

**Pre-requisites**

- _Required skills_
  - Basic Linux

- _Required setups_
  - YouTube Live Streaming Key

**Expected duration**

1 Hour

**Level**
_Intermediate_

**Resources**

Awaiting Details from Speaker

**Speaker Bio**

Rameshwar Nigam, is Director at [Pytriot Solutions Solutions LLP](https://www.pytriot.com/). He has given various talks and done various webinars in the past on IoT Security and Wireless Networking. Before working as a director at Pytriot, Mr. Rameshwar has worked in various Companies viz. CWNP, Slash Support SEZ Pvt Ltd, Aricent Group and Convergys.
Pytriot provides consultancy to various organizations and enables them to be IoT-ready following modular teaching approach which covers IoT Security and Communication.

**Social Links to your profile**  
LinkedIn: [https://www.linkedin.com/in/rameshwar-nigam-05741622/](https://www.linkedin.com/in/rameshwar-nigam-05741622/)

**Comment by Tanya-Jain** [comment]
The webinar[1] for this proposal has been conducted, hence closing the issue.

[1] https://www.youtube.com/watch?v=vjuQFOEMB0Q
