### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by sachanakshat** [asetalias/Logistics-and-Event-Contributions#22]
# Workshop on Python

**Type**
- [ ] Workshop / Hands on

**Abstract**

A workshop/hands-on which guides the audience to learn Python basics. Some coding questions will also be given for them to solve. Several programming methodologies and concepts will also be talked about.

**Pre-requisites**

- Previous programming experience would be apppreciated.

- A laptop with PyCharm and Python compiler installed.

**Expected duration**

_1 hour_

**Level**

Beginner

**Resources**

-https://www.learnpython.org/
-https://www.tutorialspoint.com/python3/python3_tutorial.pdf

**Speaker Bio**

_I am 2nd year undergraduate from Computer Science and Engineering_

**Social Links to your profile**  

Twitter: https://twitter.com/sachanakshat
Facebook: https://www.facebook.com/sachanakshat

**Month**
_July_

**Comment by vipulgupta2048** [comment]
Great to see new people proposing, be sure to cover a bit about Python 3.7
@omi10859  Can you help him with the presentation since you also took a Python 101 workshop.

**Comment by sachanakshat** [comment]
@vipulgupta2048 Thank you. Any help would really be appreciated!!!

**Comment by omi10859** [comment]
hey @sachanakshat great to know you are up for this.
- Are you making your own sliders?
here are my [slides](https://slides.com/omkaryadav/python-101/#/3) 
and for any other help ping me :)

**Comment by sachanakshat** [comment]
@omi10859 Thank you for the slides :)
I haven't made any of my slides yet. The only thing which will be there is codes XD
Will let you know.

**Comment by Tanya-Jain** [comment]
The talk has been given. Hence, closing the issue. @sachanakshat Please, share the slides or codes, if you have presented any. Thank you for contributing to ALiAS. Keep contributing to Open Source culture!
