### ISSUE TITLE
Introduction to Computer Science 101

### ISSUE THREAD

**Issue by sidhu97ss** [asetalias/Logistics-and-Event-Contributions#26]
# Introduction to Computer Science 101

**Type**
- [x]  Workshop / Hands on
- [ ] Guest Lecture
- [ ] Webinar

**Abstract**
 
**About**
We live in an age where every resource is available on the internet and keep making specialized tools and use them to make everything, but in all the chaos we forgot the the basics or don't pay heed to them.

The C language know taught as only an introductory course with obsolete study resources doesn't give the big picture. Once created by the God of Programming Dennis Ritchie , C revolutionized the Computer Science making it easy to read and write the language of computers with minimal latency.
Today most of the new languages use C as its base and continue to give an option to expand its boundaries if anyone knows C.

C remains to be the top 10 most liked programming language even today [<https://www.fullstackacademy.com/blog/nine-best-programming-languages-to-learn-2018>](https://www.fullstackacademy.com/blog/nine-best-programming-languages-to-learn-2018), with people still reluctant to learn the language. We still cant do many things without C. It is like the Swiss Knife of programming. So this introductory course will touch on its implementations , its differences, its uniqueness and many other things that you will find difficult to answer.

Will also talk about ASSEMBLY

**Pre-requisites**

Desire to know how the alien tech on your Lap works

**Expected duration**

1-hour

**Level**

Super_Beginner/Beginner/Intermediate/Advanced

**Resources**

_Add links to resources which can further be used to read up on the topic_

**Speaker Bio**

I (Siddharth Bhardwaj) am a student in first year Computer Science, who rocks a laptop with 2 Linux installations dual-booted
(and I don't use Windows)

**Social Links to your profile**  

###### - Can be done after the talk/workshop -

**Month**
_A month in which you will be available to give the talk_

**Comment by Tanya-Jain** [comment]
Thank you @sidhu97ss for willing to contribute! Kindly mention your full name. Would you like to deliver your talk this Thursday?

**Comment by sidhu97ss** [comment]
Yes I would be happy to talk on Thursday (04/10/2018)

**Comment by Tanya-Jain** [comment]
Great! We will try to finalise your talk for this Thursday and update you on the earliest.
