### ISSUE TITLE
Hacktoberfest Workshop @ Amity University on 22nd Of October

### ISSUE THREAD

**Issue by NisantaSahoo** [asetalias/Logistics-and-Event-Contributions#28]
Hacktoberfest Workshop @ Amity University on 22nd Of October

**Type**
- [x] Workshop / Hands on
- [x] Guest Lecture
- [ ] Webinar

**Abstract**

_A brief overview of what your talk is about_

**About**

_Write your talk/workshop description here and points to be covered._

**Pre-requisites**

- _Required skills_

- _Required setups_

**Expected duration**

_Time that your talk/workshop would take_

**Level**

_Beginner/Intermediate/Advanced_

**Resources**

_Add links to resources which can further be used to read up on the topic_

**Speaker Bio**

_Write a brief decription about you here_

**Social Links to your profile**  

###### - Can be done after the talk/workshop -

[Include link to slides here](link)

[Include link to video here](link)

**Month**
_A month in which you will be available to give the talk_

**Comment by vipulgupta2048** [comment]
Thanks @NisantaSahoo, for taking the workshop. 
@Tanya-Jain  Close the issue.
