### ISSUE TITLE
Introduction to Shell Scripting

### ISSUE THREAD

**Issue by swarnimarun** [asetalias/Logistics-and-Event-Contributions#29]
# Shell Scripting Basics

**Type**
- [x] Workshop / Hands on
- [ ] Guest Lecture
- [ ] Webinar

**Abstract**
_Getting started with Shell Scripting. What, Why and How?_

**About**
The talk is about getting started with Shell Scripting. Something along the lines of Beginners Guide to Shell and Scripting for Shell.
This will consist of slight to history of Shell, writing a simple Shell script, learning Shell syntax and then finally using it to automate some simple work.

**Pre-requisites**
- _None what-so-ever in terms of skills_
- _A Device with Linux OS or WSL enabled Windows - Optional but helpful_

**Expected duration**
_About an hour_

**Level**
_Beginner_

**Resources**
- https://www.shellscript.sh/
- https://www.geeksforgeeks.org/introduction-linux-shell-shell-scripting/
- https://www.tutorialspoint.com/unix/shell_scripting.htm

**Speaker Bio**

_Write a brief decription about you here_

**Social Links to your profile**  
 - Github: www.github.com/swarnimarun
 - Twitter: www.twitter.com/swarnimarun

**Project Files**

*Link:* [shell-scripting-intro](https://gitlab.com/swarnimarun/shell-scripting-intro)

Images:
![image](https://user-images.githubusercontent.com/19930870/46629841-d2934a80-cb5f-11e8-9deb-a4002f1317da.png)
![image](https://user-images.githubusercontent.com/19930870/46629901-0d957e00-cb60-11e8-9e41-45803de8afeb.png)

**Comment by Sc0rpi0n101** [comment]
You want to take a shell scripting talk now @swarnimarun?

**Comment by swarnimarun** [comment]
Works for me.

**Comment by Sc0rpi0n101** [comment]
Great, when will you be available this week?

**Comment by swarnimarun** [comment]
Pick a weekend.

**Comment by Sc0rpi0n101** [comment]
So, I'm booking this for this Saturday. Give me time by tomorrow noon.

**Comment by Sc0rpi0n101** [comment]
Great talk @swarnimarun 🎉🎉
I'm closing the issue 

You can open a new one if you want another talk
