### ISSUE TITLE
Get started with webdeveloping

### ISSUE THREAD

**Issue by steve7158** [asetalias/Logistics-and-Event-Contributions#32]
Get started with webdeveloping

Type:
wrokshop/guest lecture

Abstract:
A small talk for starting web developing to , and building a quick flask website with registrantion, home and login page. 
Some of the important topics covered in the talk are:
Flask
HTML
CSS
Bootstrap

Pre-requisites:
previous Knowledge:None required
Required setup: laptops, projectors

Expected duration
1-2hrs

level:
Beginner

Resources
Web developing start off

speakers bio:
love to write code for social good

social links to your profile:
-can be done after the talk/workshop
Github
Lnkdin
Twitter

-expected month 
March

**Comment by vipulgupta2048** [comment]
Thanks, @steve7158 
The content of the talk that you want to cover greatly exceeds the time duration stated for the same. Before @thisisayush started out with Web Development 101 on a noble prospect to teach Web Development to the students of the Amity. Little did he know it would take 6 sessions just to cover HTML.

I hope you to strongly reconsider and come with the talk of specialization, for people with an intermediate knowledge of the topic and not something general (I do see its based on Flask)

**Comment by steve7158** [comment]
Thanks for the review @vipulgupta2048  
I am working on an idea(for teaching music to student) for the upcoming dtu hackathon , it is based on combining machine learning(related to sound processing) and web development maybe i can give a talk on combining machine learning with web development.
Let me know your view on this or are we planning something else.

**Comment by vipulgupta2048** [comment]
Sure thing @steve7158, whatever your talk would be on. We like to read the final proposal for it. 
Henceforth, try re-writing the proposal so as for us to get a better idea. What content you would like to cover in the same.
