### ISSUE TITLE
Ethical Hacking & Cyber Security workshop

### ISSUE THREAD

**Issue by surmeettherebel** [asetalias/Logistics-and-Event-Contributions#33]
# Title

**Type**
- [x] Workshop / Hands on
- [ ] Guest Lecture
- [ ] Webinar

**Abstract**

_A brief overview of what your talk is about_

**About**

_Write your talk/workshop description here and points to be covered._

**Pre-requisites**

- _Required skills_

- _Required setups_

**Expected duration**

_Time that your talk/workshop would take_

**Level**

_Beginner/Intermediate/Advanced_

**Resources**

_Add links to resources which can further be used to read up on the topic_

**Speaker Bio**

_Write a brief decription about you here_

**Social Links to your profile**  

###### - Can be done after the talk/workshop -

[Include link to slides here](link)

[Include link to video here](link)

**Month**
_A month in which you will be available to give the talk_

**Comment by surmeettherebel** [comment]
Dear Sir/Ma'am

This side Surmeet Singh from Delhi. Currently working in Data center company in Noida as an Ethical Hacker & Security Engineer (VOIP) and have a 8.5 years’ experience in Ethical hacking & Security.

In 2014 I have won Facebook hacker cup competition T-Shirt and 
I would like to organize Ethical hacking Workshop at your college premises on 15th OR 16th Feb 2019. It will be a great opportunity for me to present an event in your college.

This event mainly focuses on the students to eager to be a white hat hacker. It features a brief introduction to the world of hacking starting the importance of ethical hackers and their need in today’s world scenario. Later it includes live phone hacking, call hacking, (VOIP) and more interesting topics that will definitely enhance the knowledge of the students in the field of technology.
The duration of the event depends on the number of topics covered during the ethical hacking .The average time duration will be 3-4 hrs. i.e. from 10 a.m to 1 p m.

For this event we require some technical equipment’s such as Wireless Mic, White Board, Marker and space for at least 100 students.

I will be very thankful to you if you will allow me to organize the ethical hacking event at your institute premises.

Hoping a positive reply from your side.

Please Guide Me How To Keep An Ethical Hacking Event In Your college.

A quick feedback in this regard will be highly appreciated.

Please find the attachment of other college like IIIT, Shiri Ram college, pyramid college ETC 
Alredy shered with you on your gmail (thisisayushaa@gmail.com)

**Comment by jat28468** [comment]
peer ip kese find kare ss7
