### ISSUE TITLE
Workshop on "Actions on Google" and "Alexa Skills"

### ISSUE THREAD

**Issue by sjha2048** [asetalias/Logistics-and-Event-Contributions#35]
# Title
Hands-on workshop on AoG and Alexa skills

**Type**
- [x] Workshop / Hands on
- [ ] Guest Lecture
- [ ] Webinar

**Abstract**
In this workshop, one will learn about Actions on Google and Alexa skills and at the end of the workshop, I am sure that He/She will be able to publish his/her first action/skill.

**About**
Right now Voice user interface is on the rise and people say that it's the next big thing so this workshop aims to educate the students about Alexa skills and Actions on google, basic intro to VUI concepts will be given along with a brainstorming session for the skill/action idea I'll be using templates to build the sample skill and then introduce them to the Alexa and Google Actions SDK for creation of advanced skills.

**Pre-requisites**

- Amazon Developer Account is required
  sign up for one on https://developer.amazon.com/

- A laptop with a web browser installed.

**Expected duration**

4 hours

**Level**

Beginner

**Resources**

https://developers.google.com/actions/
https://developer.amazon.com/docs/ask-overviews/build-skills-with-the-alexa-skills-kit.html

**Speaker Bio**
I am a junior year computer science student at Amity University this workshop will be conducted by me and my friend Kaushlendra as well he is also a junior year computer science student at Amity University. 

**Social Links to your profile**  
Sahil Jha - https://github.com/sjha2048
Kaushlendra - https://github.com/kaushl2208

###### - Can be done after the talk/workshop -

[Include link to slides here](link)

[Include link to video here](link)

**Month**
August/September

**Comment by sjha2048** [comment]
@Kaushl2208  anything to add?

**Comment by Kaushl2208** [comment]
@sjha2048  in the pre-requisite section add a Developer/AWS account for Alexa skill!!

**Comment by sjha2048** [comment]
anything else @Kaushl2208 ?
