### ISSUE TITLE
[Talk] Hacking from a Programmer's Perspective

### ISSUE THREAD

**Issue by pompeiifreckles** [asetalias/Logistics-and-Event-Contributions#36]
**Type**
- [x] Workshop / Hands on
- [ ] Guest Lecture
- [ ] Webinar

**Abstract**
How many hours have you wasted by attending the so called ethical hacking workshops and still feel a huge gap when you read about the security researchers who uncover bugs in Facebook and Google. Get ready for the ground zero to becoming a security researcher and not an ethical hacker, for we will discuss about cases that went unnoticed by the entire world.
Learn the real art and how to advance in it. Its not just about tools and compromising systems, Its about becoming a SECURITY RESEARCHER

**About**
The talk is gonna be fun filled and lots of live activities will be done with a bag full of memes and live websites. The talk will contain topics  
-> Google
-> SQLI and XSS
-> Programming Vulnerabilities
-> Security Misconfigurations
-> Case studies
-> Networking

**Pre-requisites**
I will try to make talk as interactive as possible and will prepare so that even a newcomer to technology understands it. 
- Basic understanding of Technology
- A little knowledge HTML/CSS 
- A little knowledge of networks

**Level**

Beginner/Intermediate

**Comment by Sc0rpi0n101** [comment]
Hey @pompeiifreckles would you like to take this workshop, or some other now?
