### ISSUE TITLE
Disscussion

### ISSUE THREAD

**Issue by atb00ker** [asetalias/Logistics-and-Event-Contributions#5]
1) I suggest the use of labels on a project as this one!
2) What all information should be in each of the event folder except Details.md and the poster?

**Comment by Tanya-Jain** [comment]
1. Working with labels is recommended.
2. Currently, only those 2 are the only required details for the repository. If there seems to be something missing, please suggest.

**Comment by Tanya-Jain** [comment]
Since there is no further discussion to be held, closing the issue for now.
