### ISSUE TITLE
[noida] [workshop] Introduction to Data Science and Machine Learning

### ISSUE THREAD

**Issue by achintya-7** [asetalias/Logistics-and-Event-Contributions#54]
# Introduction to Data Science and Machine Learning

**Type**
- [x] Workshop / Hands on
- [ ] Guest Lecture
- [ ] Webinar

**Abstract**

Getting started with the Data Science and it's various tools

**About**

Will mostly cover 2 basic algorithms i.e. Linear Regression and Logistic Regression

**Pre-requisites**

- Python
- Maths

_Required setups_
Python with Jupyter Notebook

**Expected duration**
90 min

_Time that your talk/workshop would take_
2:00 pm

**Level**

_Beginner_

**Resources**

_Goolge Colab_

**Speaker Bio**

Achintya and Gaurav are also beginners in Data Science and ML.

**Social Links to your profile**  

@achintya-7

###### - Can be done after the talk/workshop -

[Include link to slides here](link)

[Include link to video here](link)

**Month**
_October_

**Comment by ditsuke** [comment]
Executed today at the Noida campus. Bravo guys :100:
