### ISSUE TITLE
Building a Music Player in public

### ISSUE THREAD

**Issue by PranjalG420** [asetalias/Logistics-and-Event-Contributions#55]
# Building a Music Player in public

**Type**
- [ ] Workshop / Hands on
- [ ] Guest Lecture
- [x] Webinar

**Abstract**

_The talk will mainly feature Ashwin and I finishing and explaining our music player. We will also be open to suggestions from the audience about features that could improve the web application._

**About**

_We will cover the approach and process of how to tackle a project like this, including finding and fixing bugs, improving code readability, etc._

**Pre-requisites**

Some basic knowledge of:

- HTML
- CSS / Tailwind CSS
- Javascript
- React

**Expected duration**

_It should take 1 - 2 hours._

**Level**

_Beginner_

**Resources**

_N/A_

**Speaker Bio**

_I'm an aspiring web developer who likes to explore how the web works._

**Social Links to your profile**  
https://pranjalg420.vercel.app/
https://github.com/pranjalG420

###### - Can be done after the talk/workshop -

_N/A_

**Month**
_November_

**Comment by ditsuke** [comment]
Thanks, planned for 12 November 2022, 9PM IST over on the ALiAS Discord!
https://discord.gg/5SBG78VR?event=1040641155685175346

**Comment by ditsuke** [comment]
Closing, thanks!
