### ISSUE TITLE
Flutter 101

### ISSUE THREAD

**Issue by achintya-7** [asetalias/Logistics-and-Event-Contributions#60]
### Type

Workshop / Hands-on

### Location

Online (Discord, YouTube Stream or Zoom/Jitsi)

### About

Getting started with Flutter

### Pre-requisites

Basic OOPs

### Duration

1 hour 

### Level

Beginner

### Resources

Laptop

### Speakers

@achintya-7

**Comment by ditsuke** [comment]
Finalised for Sunday the 20th, 6:00PM IST.

**Comment by ditsuke** [comment]
Executed successfully. Cheers!
