### ISSUE TITLE
[Proposal] Generic advice for would be engineers

### ISSUE THREAD

**Issue by vinayaknayar** [asetalias/Logistics-and-Event-Contributions#65]
### Type

Talk

### Location

Campus: Noida

### About

Talk is proposed for the alumni meet and interaction event(27th Jan 23). Anuvrat as a speaker will be taking the session.

### Pre-requisites

- _wanna be engineer_
- _working brain_
### Duration

40mins

### Level

None

### Resources

_NIL_

### Speakers

Anuvrat Parashar

**Comment by ditsuke** [comment]
Successfully organized at the alumni meet on the 27th of Jan. Thanks!
