### ISSUE TITLE
[Proposal] Learn, Unlearn and Learn Again 

### ISSUE THREAD

**Issue by vinayaknayar** [asetalias/Logistics-and-Event-Contributions#66]
### Type

Talk

### Location

Campus: Noida

### About

Aniket Maithani as a speaker will be taking a session on the topic mentioned above . Talk should be scheduled for the Alumni-meet and Interaction event dated 27th Jan 2023.

### Pre-requisites

- _Amitian_
- _common sense_

### Duration

30mins

### Level

None

### Resources

_NIL_

### Speakers

Aniket Maithani

**Comment by ditsuke** [comment]
Successfully organized at the alumni meet on the 27th of Jan. Thanks!
